version: '2'

services:
  api_dev:
    container_name: ${PROJET_NAME}_api_dev
    build: ./server/
    environment:
      - VIRTUAL_HOST=api.${PROJET_NAME}.local
    volumes : 
      - ./server/:/usr/src/app:rw
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
  
  mongo:
    container_name: ${PROJET_NAME}_mongo_dev
    image: mongo
    environment:
      - VIRTUAL_HOST=mongo.${PROJET_NAME}db.local
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    environment:
      - VIRTUAL_HOST=app.${PROJET_NAME}db.local
    depends_on:
      - mongo
    ports:
      - 3300:3000
