version: '2'

services:
  api_dev:
    container_name: ${PROJET_NAME}_backend_dev
    build: ./server/
    environment:
      - VIRTUAL_HOST=api.${PROJET_NAME}.local
    volumes : 
      - ./server/:/usr/src/app:rw
    restart: alwaysports:
      - "80:3000"
    links:
      - mongo
  
  mongo:
    container_name: ${PROJET_NAME}_mongo_dev
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
